### ISSUE TITLE
A crap sound

### ISSUE THREAD

**Issue by nickbash11** [rkinnett/ESP32-VBAN-Network-Audio-Player#2]
When I route the audio stream to the ESP32-VBAN device I got a strange noise in the "rest mode". The example is in attachment. The noise appears in accurate when I switch stream to the ESP32.
[esp32-vban-noise.wav.zip](https://github.com/rkinnett/ESP32-VBAN-Network-Audio-Player/files/7491099/esp32-vban-noise.wav.zip)

For experiments I use VBAN for command line from here https://github.com/quiniouben/vban
```

~$ vban_emitter -i 10.30.1.6 -p 6980 -s Stream1 -b alsa -l 3 -n 1
vban_emitter version 2.1.0

Info: socket_open: opening socket with port 6980
Info: socket_open with port: 6980
Info: audio_init: config is direction in, backend alsa, device , buffer size 1024
Info: audio_backend_get_by_name: found backend alsa
Info: audio_set_map_config: new map config is nb channels 0
Info: audio_set_stream_config: new stream config is nb channels 1, sample rate 44100, bit_fmt 16I
^C
~$
```

I have already had a positive experience with this command line tools by using it together with ESP8266+PCM5102 and it works pretty good with rate 16000 Hz. https://github.com/flyingKenny/VBAN-Receptor-ESP8266-I2S

**Comment by rkinnett** [comment]
Sorry, I'm just now seeing this.  Yeah, that sounds terrible.

I see that you're streaming 16 bit which is good, and I think 44100 Hz should work.

Have you tried using the Voicemeeter GUI as described in the readme?

What do you mean by "rest mode" and "switch stream"?  What circuit do you have on the analog output GPIO pin?  Do you hear acceptable audio while playing sound from your computer, and just hear that noise when there is no sound being generated by the computer, or is that background noise continuously present?  Or do you only hear noise when you stop the VBAN stream?

It's possible this sketch doesn't correctly zero the DMA buffer when a VBAN stream is interrupted.

**Comment by rkinnett** [comment]
Ooh, that project from @flyingKenny looks much cleaner than mine.  I wish I had found that back in 2020!  Thanks for the reference.
